#!/usr/bin/env bash
# Installs Nginx server

# Update package repositories and install Nginx
apt-get update
apt-get -y install nginx

# Configure firewall to allow Nginx HTTP traffic
ufw allow 'Nginx HTTP'

# Set up a basic HTML page
echo "Hello World!" > /var/www/html/index.html

# Start Nginx service
service nginx restart
