#!/usr/bin/env bash
# The redirection must be a 301 Moved Permanently

sudo apt-get update
sudo apt-get install -y nginx
#ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.blog.ehoneahobed.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
