#!/usr/bin/env bash
# Bash script to configure HAProxy on a new Ubuntu machine

# Function to install packages
function install_package() {
    package_name=$1
    if ! dpkg -l | grep -q $package_name; then
        echo "Installing $package_name..."
        sudo apt-get update -y -qq && \
        sudo apt-get install -y $package_name -qq
    else
        echo "$package_name is already installed."
    fi
}

# Install HAProxy
install_package haproxy

# Backup default HAProxy configuration
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
defaults
    mode http
    timeout client 15s
    timeout connect 10s
    timeout server 15s
    timeout http-request 10s

frontend augustineemeka-tech-frontend
    bind *:80
    default_backend augustineemeka-tech-backend

backend augustineemeka-tech-backend
    balance roundrobin
    server 488939-web-01 <IP_of_web_01>:80 check
    server 488939-web-02 <IP_of_web_02>:80 check
EOF

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

# Restart HAProxy service
sudo service haproxy restart

echo "HAProxy configured successfully!"
