#!/usr/bin/env bash
# Bash script to configure HAProxy on a new Ubuntu machine

# Install HAProxy
sudo apt update -y
sudo apt install haproxy -y

# Make a backup of the configuration file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
defaults
    mode http
    timeout client 15s
    timeout connect 10s
    timeout server 15s
    timeout http-request 10s

frontend augustineemeka-tech-frontend
    bind *:80
    default_backend augustineemeka-tech-backend

backend augustineemeka-tech-backend
    balance roundrobin
    server 488939-web-01 54.90.0.247:80 check
    server 488939-web-02 54.160.86.47:80 check
EOF

# Enable HAProxy
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

# Start HAProxy
sudo service haproxy start
