#!/usr/bin/env bash
# Install and configure HAproxy on your wb-01 server.

# Install and configure HAproxy on your wb-01 server.
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y update
sudo apt-get -y install haproxy

# Listen to web1 and web2 servers  
sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sed -i -e '$a\listen balancer\n\tbind :80\n\tbalance roundrobin\n\tserver 61590-web-01 204.7.186:80 check\n\tserver 61590-web-02 3.83.245.14:80 check\n' /etc/haproxy/haproxy.cfg

sudo service haproxy restart
