#!/usr/bin/env bash
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal


pid_file="/var/run/myscript.pid"

# Function to handle cleanup
cleanup() {
    rm -f "$pid_file"
    exit
}

# Function to handle SIGTERM signal
sigterm_handler() {
    echo "I hate the kill command"
    cleanup
}

# Function to handle SIGINT signal
sigint_handler() {
    echo "Y U no love me?!"
}

# Create the PID file
echo $$ > "$pid_file"

# Display messages indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
    trap sigterm_handler SIGTERM
    trap sigint_handler SIGINT
    trap cleanup SIGQUIT
done
