#!/usr/bin/env bash
#Your script should only display
#username
#user id
#Home directory path for the user

myfile="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < "$myfile"
